version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
      - grafana
    networks:
      - taskito-network
      - loki

  api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.local
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis

    depends_on:
      - postgres
      - redis
      - loki
    networks:
      - taskito-network
      - loki

  postgres:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    networks:
      - taskito-network

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - taskito-network

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - loki

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost/api
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Allow self-signed certificates in development
    depends_on:
      - api
      - loki
    networks:
      - taskito-network
      - loki

volumes:
  postgres-data:
  redis-data:

networks:
  taskito-network:
    driver: bridge
  loki:
    driver: bridge
